services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: emotionflix_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seniorproject450
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/emotionflix_dev
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: